### ISSUE TITLE
关于ns3中的wifi模型

### ISSUE THREAD

**Issue by anlitiantian** [MemoryOfLove/MemoryOfLove.github.io#1]
你好，我在http://www.jluyeyu.com/ns3/11.ns3%20wifi%E6%A8%A1%E5%9D%97%E6%B5%81%E7%A8%8B%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/ 看到你写的关于WiFi模型的内容，有个问题想请教一下，可以添加一下你的联系方式吗

**Comment by MemoryOfLove** [comment]
qq:554737661
